name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test_smart_contracts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - uses: actions/setup-python@v2
    - name: "Install SmartPy"
      run: |
        curl -s https://smartpy.io/releases/20210405-4dc8e0b9b9fc5c58a933b461dbb10f643329716b/cli/install.sh | sh -s -- local-install ~/smartpy-cli
    - name: "Build and Test Smart Contracts"
      run: |
        ./compile.sh
